#!/bin/bash
set -e

baseDir=/sys/kernel/config/usb_gadget/zero-hid

rm ${baseDir}/configs/c.1/hid.usb0
rmdir ${baseDir}/configs/c.1/strings/0x409
rmdir ${baseDir}/configs/c.1

rmdir ${baseDir}/strings/0x409
rmdir ${baseDir}/functions/hid.usb0

rmdir ${baseDir}
