#!/bin/bash
set -e

cd /sys/kernel/config/usb_gadget
mkdir zero-hid && cd zero-hid

echo 0x1d6b > idVendor   # Linux Foundation
echo 0x0104 > idProduct  # Multifunction Composite Gadget
echo 0x0100 > bcdDevice  # v.1.0.0
echo 0x0200 > bcdUSB     # USB2

#echo 0x01   > bDeviceClass
#echo 0x01   > bDeviceSubClass
#echo 0x01   > bDeviceProtocol

wDir="strings/0x409"
mkdir -p ${wDir}

echo "0xdeadbeef" > ${wDir}/serialnumber
echo "0xdeadbeef" > ${wDir}/manufacturer
echo "0xdeadbeef" > ${wDir}/product

wDir="configs/c.1/strings/0x409"
mkdir -p ${wDir}

echo "Config 1: Blah blah" > ${wDir}/configuration
echo 250 > configs/c.1/MaxPower

wDir="functions/hid.usb0"
mkdir -p ${wDir}

echo 1 > ${wDir}/protocol
echo 1 > ${wDir}/subclass
echo 8 > ${wDir}/report_length
echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x95\\x01\\x75\\x08\\x81\\x03\\x95\\x05\\x75\\x01\\x05\\x08\\x19\\x01\\x29\\x05\\x91\\x02\\x95\\x01\\x75\\x03\\x91\\x03\\x95\\x06\\x75\\x08\\x15\\x00\\x25\\x65\\x05\\x07\\x19\\x00\\x29\\x65\\x81\\x00\\xc0 > ${wDir}/report_desc
#echo -ne \\x05\\x01\\x09\\x06\\xa1\\x01\\x05\\x07\\x19\\xe0\\x29\\xe7\\x15\\x00\\x25\\x01\\x75\\x01\\x95\\x08\\x81\\x02\\x05\\x0C\\x95\\x01\\x75\\x08\\x15\\x00\\x26\\xFF\\x00\\x19\\x00\\x29\\xFF\\x81\\x00\\x05\\x08\\x19\\x01\\x29\\x08\\x95\\x08\\x75\\x01\\x91\\x02\\x05\\x07\\x95\\x06\\x75\\x08\\x15\\x00\\x26\\xE7\\x00\\x19\\x00\\x29\\xE7\\x81\\x00\\xc0 > ${wDir}/report_desc

ln -s functions/hid.usb0 configs/c.1
ls /sys/class/udc > UDC

chmod o+rw /dev/hidg0
